### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-emfcloud/ecore-glsp#105]
Some examples in /client/workspace have issues:
STM and glsp-graph show a dirty indicator directly after opening. Probably the layout is not saved correctly
"Empty" is not empty, but has weird classes in it.

**Comment by CamilleLetavernier** [comment]
The "empty.ecore" model has been cleaned up with PR #108

**Comment by eneufeld** [comment]
All issues should be fixed now. Please open a new issue if something still doesn't work.
