### ISSUE TITLE
Creation of genmodel does not allow confiming

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-emfcloud/ecore-glsp#107]
F1 => Generate GenModel => enter => enter again => Dialog does not close, even when entering a name. It should ideally suggest a default output folder to be confirmed via enter

**Comment by ndoschek** [comment]
The problem was that the generator needs an underlying `*.ecore` resource to be able to create the GenModel. This was not ensured, so the dialog misbehaved.
Please see pr #108 for more details.
