### ISSUE TITLE
Nodes are not displayed when opening two diagrams

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-emfcloud/ecore-glsp#124]
When I open two digrams directly after each other, the node on the second diagram are not displayed, see this screenshot:

![bugvideo](https://user-images.githubusercontent.com/1052615/157945861-bf925e89-7d7b-454f-a8f2-3b3f40731312.gif)

**Comment by JonasHelming** [comment]
@CamilleLetavernier

**Comment by ndoschek** [comment]
This is a duplicate of https://github.com/eclipse-emfcloud/ecore-glsp/issues/23

**Comment by ndoschek** [comment]
This is a duplicate of https://github.com/eclipse-emfcloud/ecore-glsp/issues/23
