### ISSUE TITLE
CI build fails on master with incorrect node version

### ISSUE THREAD

**Issue by vhemery** [eclipse-emfcloud/ecore-glsp#126]
https://ci.eclipse.org/emfcloud/job/eclipse-emfcloud/job/ecore-glsp/job/master/ build hasn't succeded in a while. So I tried and launched it.

I got a few hicups with unreachable pods (stuck builds I deleted for the sake of readability), but appart from that, I get the following build error (e.g. [build 23](https://ci.eclipse.org/emfcloud/job/eclipse-emfcloud/job/ecore-glsp/job/master/23/console)):
`error @: The engine "node" is incompatible with this module. Expected version ">=12.14.1 <13". Got "14.20.1"`

It does seem strange to me as the dockerfile is based on node 12...

**Comment by ndoschek** [comment]
Hi @vhemery, thanks for pointing that out!
I will update the docker image for the Jenkins build to ensure Node 12 is used for builiding.
See PR #113
