### ISSUE TITLE
Improve the UI for creating Ecore files, GenModel files and triggering CodeGen

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-emfcloud/ecore-glsp#13]
Original issue: https://github.com/eclipsesource/ecore-glsp/issues/131

The command-based approach is simple, but not especially user-friendly. It can be hard to know what each parameter means, and especially what the "path" values expect (Absolute path? Relative path? Relative to the workspace, or to the selection? etc.). Also, the commands expect some specific selection (Folder, Ecore file, Ecore genmodel...) and will fail if the selection is incorrect; although without any helpful explanation for the user.

This must be improved. At least, we need:

* Proper parameter documentation
* Proper error-reporting to the user

Ideally:

* Live-validation of the parameters & selection (For a command-based version)
* A nice form-based wizard (For improved user-friendliness)

**Comment by ndoschek** [comment]
For creating Ecore files, the creation of a dedicated `*.enotation` file is also needed.
