### ISSUE TITLE
Upgrades to @theia/filesystem breaks EcoreCommandContribution

### ISSUE THREAD

**Issue by drkstr101** [eclipse-emfcloud/ecore-glsp#56]
RE: https://github.com/eclipse-theia/theia/pull/7908

Hello,

I didn't see this on the roadmap anywhere, so I thought I would open up a ticket and see if I can make some progress on it.

**Goal:** Support latest Theia release (`1.7.0` as of now) 

**Problem:** Updates to `@theia/filesystem` are incompatible with `EcoreCommandContribution`

**Proposed Solution:** 
1. Update `FileStat` import to the new location
2. Replace calls to `FileSystem` with equiv in `FileService`
3. Fix any additional type errors as needed

**Comment by CamilleLetavernier** [comment]
Hi Aaron,

Ecore-GLSP follows the GLSP dependency chain, which is currently limited to Theia 1.4. In turn, GLSP depends on Sprotty, which requires the (deprecated) languages support from Theia 1.4, thus can't update to anything more recent at the moment. But there are some plans to update Sprotty in the near future, so GLSP (and then Ecore-GLSP) should be able to catch up with Theia versions.

Also, regarding Ecore-GLSP, we plan on removing all filesystem-related operations from Theia (Except for the Explorer), to delegate everything to the Diagram/ModelServer (Just like it's currently done for Diagrams at the moment, i.e. relying on JSonRPC). So, all of the EcoreCommandContribution commands should disappear (eventually :) )

**Comment by drkstr101** [comment]
Good deal! I will just close this out for now. I am slogging through `language-server-extension` locally, but it sounds like this will not even be needed once everything delegates to `model-server`. Please let me know if there is anything I assist with.

Cheers!
