### ISSUE TITLE
[Model Server] Create bi-directional references

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-emfcloud/ecore-glsp#58]
i directional references are a bit specific, as they require creating multiple related elements. Atomically, we need to:

- Create the first reference (A)
- Create the second reference (B)
- Set A as the opposite of B

The problem is that until A and B are actually created on the Model Server side, it is not possible to properly define the Set command.

**Comment by ndoschek** [comment]
Closed via #73
