### ISSUE TITLE
[Model Server] Delete elements

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-emfcloud/ecore-glsp#59]
The Model Server should support deleting existing elements.

In most cases, this corresponds to either a Set(null) or a Remove(element) commands. However, for ETypes (EClass...), we also want to remove all EReferences typed with the deleted EType. This is required in Ecore GLSP because we only show EReferences as arrows between 2 classifiers; so untyped EReferences are not supported and cannot be modified (since they can't be displayed).

**Comment by ndoschek** [comment]
Major part is done (see PR #69), removing generalization edges still has to be completed
(i.e. removing entry from eSuperTypes of a an eClass)
Also see issue #19

**Comment by CamilleLetavernier** [comment]
Fixed on the Modelserver branch with https://github.com/eclipse-emfcloud/ecore-glsp/pull/71
